### ISSUE TITLE
v4.0.2 broke our redis deployments

### ISSUE THREAD

**Issue by poloka** [redis/redis-rb#779]
In a recent upgrade of my servers the consumption of redis-4.0.2 broke our deployments in an attempt to evaluate localhost at 127.0.0.1 rather than using our config for our sentinels.  Wanted to review the changes but I only see a v4.0.1 tag and not a v4.0.2.  Was this version removed?  if so, rubygems still indicates there is a version.

https://rubygems.org/gems/redis/versions/4.0.2

**Comment by byroot** [comment]
Hum, the tag is indeed missing, that's weird. I'll create it in a second.

Can you be more specific about what is broken? Got an exception? backtrace?

**Comment by byroot** [comment]
Ok, I figured why the tag wasn't pushed.

Fixed now, here's the diff: https://github.com/redis/redis-rb/compare/v4.0.1...v4.0.2

Please let me know if you figure your issue.

**Comment by poloka** [comment]
Looking at my Gemfile.lock of my rails application I can see
```
-    redis (4.0.1)
-    redis-objects (1.4.0)
+    redis (4.0.2)
+    redis-objects (1.4.2)
```
The error I see in our splunk queries notes
```
Failed to connect to redis #<Redis::CannotConnectError: Error connecting to Redis on 127.0.0.1:6379 (Errno::ECONNREFUSED)>
```
The rails app is running on one virtual machine and using sentinels configured on separate VMs with our redis database on another set of VMs.

**Comment by byroot** [comment]
You might want to inspect the connection objects from a rails console to see if the parameters are properly parsed / handled.

Possibly one or mutiple of password / host / port isn't considered by the client.

**Comment by poloka** [comment]
I'll dig in more but initially running locally looks to to walk through the sentinels here for one that responds.
https://github.com/redis/redis-rb/blob/v4.0.2/lib/redis/client.rb#L556-L561

**Comment by tina-tran** [comment]
Hi,

I have the same error when deploying to Heroku. It had worked fine before I updated the gems.
My config: 
```
ruby 2.3.1p112
rails-4.2.10
redis-4.0.2
```
I downgraded Redis to 4.0.1, I still have the same error:
```
Redis::CannotConnectError: Error connecting to Redis on 127.0.0.1:6379 (Errno::ECONNREFUSED)
remote:        /tmp/build_bb0aab9efc24beefd4555b836ba50433/vendor/bundle/ruby/2.3.0/gems/redis-4.0.1/lib/redis/client.rb:344:in `rescue in establish_connection'
remote:        /tmp/build_bb0aab9efc24beefd4555b836ba50433/vendor/bundle/ruby/2.3.0/gems/redis-4.0.1/lib/redis/client.rb:329:in `establish_connection'
remote:        /tmp/build_bb0aab9efc24beefd4555b836ba50433/vendor/bundle/ruby/2.3.0/gems/redis-4.0.1/lib/redis/client.rb:99:in `block in connect'
remote:        /tmp/build_bb0aab9efc24beefd4555b836ba50433/vendor/bundle/ruby/2.3.0/gems/redis-4.0.1/lib/redis/client.rb:291:in `with_reconnect'
remote:        /tmp/build_bb0aab9efc24beefd4555b836ba50433/vendor/bundle/ruby/2.3.0/gems/redis-4.0.1/lib/redis/client.rb:98:in `connect'
remote:        /tmp/build_bb0aab9efc24beefd4555b836ba50433/vendor/bundle/ruby/2.3.0/gems/redis-4.0.1/lib/redis/client.rb:363:in `ensure_connected'
remote:        /tmp/build_bb0aab9efc24beefd4555b836ba50433/vendor/bundle/ruby/2.3.0/gems/redis-4.0.1/lib/redis/client.rb:219:in `block in process'
remote:        /tmp/build_bb0aab9efc24beefd4555b836ba50433/vendor/bundle/ruby/2.3.0/gems/redis-4.0.1/lib/redis/client.rb:304:in `logging'
remote:        /tmp/build_bb0aab9efc24beefd4555b836ba50433/vendor/bundle/ruby/2.3.0/gems/redis-4.0.1/lib/redis/client.rb:218:in `process'
remote:        /tmp/build_bb0aab9efc24beefd4555b836ba50433/vendor/bundle/ruby/2.3.0/gems/redis-4.0.1/lib/redis/client.rb:118:in `call'
remote:        /tmp/build_bb0aab9efc24beefd4555b836ba50433/vendor/bundle/ruby/2.3.0/gems/redis-4.0.1/lib/redis.rb:543:in `block in keys'
remote:        /tmp/build_bb0aab9efc24beefd4555b836ba50433/vendor/bundle/ruby/2.3.0/gems/redis-4.0.1/lib/redis.rb:45:in `block in synchronize'
remote:        /tmp/build_bb0aab9efc24beefd4555b836ba50433/vendor/bundle/ruby/2.3.0/gems/redis-4.0.1/lib/redis.rb:45:in `synchronize'
remote:        /tmp/build_bb0aab9efc24beefd4555b836ba50433/vendor/bundle/ruby/2.3.0/gems/redis-4.0.1/lib/redis.rb:542:in `keys'
remote:        /tmp/build_bb0aab9efc24beefd4555b836ba50433/config/application.rb:49:in `block in <class:Application>'
remote:        /tmp/build_bb0aab9efc24beefd4555b836ba50433/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.10/lib/active_support/lazy_load_hooks.rb:36:in `execute_hook'
remote:        /tmp/build_bb0aab9efc24beefd4555b836ba50433/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.10/lib/active_support/lazy_load_hooks.rb:45:in `block in run_load_hooks'
remote:        /tmp/build_bb0aab9efc24beefd4555b836ba50433/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.10/lib/active_support/lazy_load_hooks.rb:44:in `each'
remote:        /tmp/build_bb0aab9efc24beefd4555b836ba50433/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.10/lib/active_support/lazy_load_hooks.rb:44:in `run_load_hooks'
remote:        /tmp/build_bb0aab9efc24beefd4555b836ba50433/vendor/bundle/ruby/2.3.0/gems/railties-4.2.10/lib/rails/application/finisher.rb:62:in `block in <module:Finisher>'
remote:        /tmp/build_bb0aab9efc24beefd4555b836ba50433/vendor/bundle/ruby/2.3.0/gems/railties-4.2.10/lib/rails/initializable.rb:30:in `instance_exec'
remote:        /tmp/build_bb0aab9efc24beefd4555b836ba50433/vendor/bundle/ruby/2.3.0/gems/railties-4.2.10/lib/rails/initializable.rb:30:in `run'
remote:        /tmp/build_bb0aab9efc24beefd4555b836ba50433/vendor/bundle/ruby/2.3.0/gems/railties-4.2.10/lib/rails/initializable.rb:55:in `block in run_initializers'
remote:        /tmp/build_bb0aab9efc24beefd4555b836ba50433/vendor/bundle/ruby/2.3.0/gems/railties-4.2.10/lib/rails/initializable.rb:54:in `run_initializers'
remote:        /tmp/build_bb0aab9efc24beefd4555b836ba50433/vendor/bundle/ruby/2.3.0/gems/railties-4.2.10/lib/rails/application.rb:352:in `initialize!'
remote:        /tmp/build_bb0aab9efc24beefd4555b836ba50433/config/environment.rb:5:in `<top (required)>'
remote:        /tmp/build_bb0aab9efc24beefd4555b836ba50433/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:274:in `require'
remote:        /tmp/build_bb0aab9efc24beefd4555b836ba50433/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:274:in `block in require'
remote:        /tmp/build_bb0aab9efc24beefd4555b836ba50433/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:240:in `load_dependency'
remote:        /tmp/build_bb0aab9efc24beefd4555b836ba50433/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:274:in `require'
remote:        /tmp/build_bb0aab9efc24beefd4555b836ba50433/vendor/bundle/ruby/2.3.0/gems/railties-4.2.10/lib/rails/application.rb:328:in `require_environment!'
remote:        /tmp/build_bb0aab9efc24beefd4555b836ba50433/vendor/bundle/ruby/2.3.0/gems/railties-4.2.10/lib/rails/application.rb:457:in `block in run_tasks_blocks'
remote:        /tmp/build_bb0aab9efc24beefd4555b836ba50433/vendor/bundle/ruby/2.3.0/gems/sprockets-rails-3.2.1/lib/sprockets/rails/task.rb:62:in `block (2 levels) in define'
remote:        /tmp/build_bb0aab9efc24beefd4555b836ba50433/vendor/bundle/ruby/2.3.0/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
remote:        
remote:        Caused by:
remote:        Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:6379
remote:        /tmp/build_bb0aab9efc24beefd4555b836ba50433/vendor/bundle/ruby/2.3.0/gems/redis-4.0.1/lib/redis/connection/ruby.rb:187:in `rescue in connect_addrinfo'
remote:        /tmp/build_bb0aab9efc24beefd4555b836ba50433/vendor/bundle/ruby/2.3.0/gems/redis-4.0.1/lib/redis/connection/ruby.rb:179:in `connect_addrinfo'
remote:        /tmp/build_bb0aab9efc24beefd4555b836ba50433/vendor/bundle/ruby/2.3.0/gems/redis-4.0.1/lib/redis/connection/ruby.rb:220:in `block in connect'
remote:        /tmp/build_bb0aab9efc24beefd4555b836ba50433/vendor/bundle/ruby/2.3.0/gems/redis-4.0.1/lib/redis/connection/ruby.rb:218:in `each'
remote:        /tmp/build_bb0aab9efc24beefd4555b836ba50433/vendor/bundle/ruby/2.3.0/gems/redis-4.0.1/lib/redis/connection/ruby.rb:218:in `each_with_index'
remote:        /tmp/build_bb0aab9efc24beefd4555b836ba50433/vendor/bundle/ruby/2.3.0/gems/redis-4.0.1/lib/redis/connection/ruby.rb:218:in `connect'
remote:        /tmp/build_bb0aab9efc24beefd4555b836ba50433/vendor/bundle/ruby/2.3.0/gems/redis-4.0.1/lib/redis/connection/ruby.rb:293:in `connect'
remote:        /tmp/build_bb0aab9efc24beefd4555b836ba50433/vendor/bundle/ruby/2.3.0/gems/redis-4.0.1/lib/redis/client.rb:334:in `establish_connection'
remote:        /tmp/build_bb0aab9efc24beefd4555b836ba50433/vendor/bundle/ruby/2.3.0/gems/redis-4.0.1/lib/redis/client.rb:99:in `block in connect'
remote:        /tmp/build_bb0aab9efc24beefd4555b836ba50433/vendor/bundle/ruby/2.3.0/gems/redis-4.0.1/lib/redis/client.rb:291:in `with_reconnect'
remote:        /tmp/build_bb0aab9efc24beefd4555b836ba50433/vendor/bundle/ruby/2.3.0/gems/redis-4.0.1/lib/redis/client.rb:98:in `connect'
remote:        /tmp/build_bb0aab9efc24beefd4555b836ba50433/vendor/bundle/ruby/2.3.0/gems/redis-4.0.1/lib/redis/client.rb:363:in `ensure_connected'
remote:        /tmp/build_bb0aab9efc24beefd4555b836ba50433/vendor/bundle/ruby/2.3.0/gems/redis-4.0.1/lib/redis/client.rb:219:in `block in process'
remote:        /tmp/build_bb0aab9efc24beefd4555b836ba50433/vendor/bundle/ruby/2.3.0/gems/redis-4.0.1/lib/redis/client.rb:304:in `logging'
remote:        /tmp/build_bb0aab9efc24beefd4555b836ba50433/vendor/bundle/ruby/2.3.0/gems/redis-4.0.1/lib/redis/client.rb:218:in `process'
remote:        /tmp/build_bb0aab9efc24beefd4555b836ba50433/vendor/bundle/ruby/2.3.0/gems/redis-4.0.1/lib/redis/client.rb:118:in `call'
remote:        /tmp/build_bb0aab9efc24beefd4555b836ba50433/vendor/bundle/ruby/2.3.0/gems/redis-4.0.1/lib/redis.rb:543:in `block in keys'
remote:        /tmp/build_bb0aab9efc24beefd4555b836ba50433/vendor/bundle/ruby/2.3.0/gems/redis-4.0.1/lib/redis.rb:45:in `block in synchronize'
remote:        /tmp/build_bb0aab9efc24beefd4555b836ba50433/vendor/bundle/ruby/2.3.0/gems/redis-4.0.1/lib/redis.rb:45:in `synchronize'
remote:        /tmp/build_bb0aab9efc24beefd4555b836ba50433/vendor/bundle/ruby/2.3.0/gems/redis-4.0.1/lib/redis.rb:542:in `keys'
remote:        /tmp/build_bb0aab9efc24beefd4555b836ba50433/config/application.rb:49:in `block in <class:Application>'
remote:        /tmp/build_bb0aab9efc24beefd4555b836ba50433/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.10/lib/active_support/lazy_load_hooks.rb:36:in `execute_hook'
remote:        /tmp/build_bb0aab9efc24beefd4555b836ba50433/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.10/lib/active_support/lazy_load_hooks.rb:45:in `block in run_load_hooks'
remote:        /tmp/build_bb0aab9efc24beefd4555b836ba50433/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.10/lib/active_support/lazy_load_hooks.rb:44:in `each'
remote:        /tmp/build_bb0aab9efc24beefd4555b836ba50433/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.10/lib/active_support/lazy_load_hooks.rb:44:in `run_load_hooks'
remote:        /tmp/build_bb0aab9efc24beefd4555b836ba50433/vendor/bundle/ruby/2.3.0/gems/railties-4.2.10/lib/rails/application/finisher.rb:62:in `block in <module:Finisher>'
remote:        /tmp/build_bb0aab9efc24beefd4555b836ba50433/vendor/bundle/ruby/2.3.0/gems/railties-4.2.10/lib/rails/initializable.rb:30:in `instance_exec'
remote:        /tmp/build_bb0aab9efc24beefd4555b836ba50433/vendor/bundle/ruby/2.3.0/gems/railties-4.2.10/lib/rails/initializable.rb:30:in `run'
remote:        /tmp/build_bb0aab9efc24beefd4555b836ba50433/vendor/bundle/ruby/2.3.0/gems/railties-4.2.10/lib/rails/initializable.rb:55:in `block in run_initializers'
remote:        /tmp/build_bb0aab9efc24beefd4555b836ba50433/vendor/bundle/ruby/2.3.0/gems/railties-4.2.10/lib/rails/initializable.rb:54:in `run_initializers'
remote:        /tmp/build_bb0aab9efc24beefd4555b836ba50433/vendor/bundle/ruby/2.3.0/gems/railties-4.2.10/lib/rails/application.rb:352:in `initialize!'
remote:        /tmp/build_bb0aab9efc24beefd4555b836ba50433/config/environment.rb:5:in `<top (required)>'
remote:        /tmp/build_bb0aab9efc24beefd4555b836ba50433/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:274:in `require'
remote:        /tmp/build_bb0aab9efc24beefd4555b836ba50433/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:274:in `block in require'
remote:        /tmp/build_bb0aab9efc24beefd4555b836ba50433/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:240:in `load_dependency'
remote:        /tmp/build_bb0aab9efc24beefd4555b836ba50433/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:274:in `require'
remote:        /tmp/build_bb0aab9efc24beefd4555b836ba50433/vendor/bundle/ruby/2.3.0/gems/railties-4.2.10/lib/rails/application.rb:328:in `require_environment!'
remote:        /tmp/build_bb0aab9efc24beefd4555b836ba50433/vendor/bundle/ruby/2.3.0/gems/railties-4.2.10/lib/rails/application.rb:457:in `block in run_tasks_blocks'
remote:        /tmp/build_bb0aab9efc24beefd4555b836ba50433/vendor/bundle/ruby/2.3.0/gems/sprockets-rails-3.2.1/lib/sprockets/rails/task.rb:62:in `block (2 levels) in define'
remote:        /tmp/build_bb0aab9efc24beefd4555b836ba50433/vendor/bundle/ruby/2.3.0/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
remote:        
remote:        Caused by:
remote:        IO::EINPROGRESSWaitWritable: Operation now in progress - connect(2) would block
remote:        /tmp/build_bb0aab9efc24beefd4555b836ba50433/vendor/bundle/ruby/2.3.0/gems/redis-4.0.1/lib/redis/connection/ruby.rb:180:in `connect_addrinfo'
remote:        /tmp/build_bb0aab9efc24beefd4555b836ba50433/vendor/bundle/ruby/2.3.0/gems/redis-4.0.1/lib/redis/connection/ruby.rb:220:in `block in connect'
remote:        /tmp/build_bb0aab9efc24beefd4555b836ba50433/vendor/bundle/ruby/2.3.0/gems/redis-4.0.1/lib/redis/connection/ruby.rb:218:in `each'
remote:        /tmp/build_bb0aab9efc24beefd4555b836ba50433/vendor/bundle/ruby/2.3.0/gems/redis-4.0.1/lib/redis/connection/ruby.rb:218:in `each_with_index'
remote:        /tmp/build_bb0aab9efc24beefd4555b836ba50433/vendor/bundle/ruby/2.3.0/gems/redis-4.0.1/lib/redis/connection/ruby.rb:218:in `connect'
remote:        /tmp/build_bb0aab9efc24beefd4555b836ba50433/vendor/bundle/ruby/2.3.0/gems/redis-4.0.1/lib/redis/connection/ruby.rb:293:in `connect'
remote:        /tmp/build_bb0aab9efc24beefd4555b836ba50433/vendor/bundle/ruby/2.3.0/gems/redis-4.0.1/lib/redis/client.rb:334:in `establish_connection'
remote:        /tmp/build_bb0aab9efc24beefd4555b836ba50433/vendor/bundle/ruby/2.3.0/gems/redis-4.0.1/lib/redis/client.rb:99:in `block in connect'
remote:        /tmp/build_bb0aab9efc24beefd4555b836ba50433/vendor/bundle/ruby/2.3.0/gems/redis-4.0.1/lib/redis/client.rb:291:in `with_reconnect'
remote:        /tmp/build_bb0aab9efc24beefd4555b836ba50433/vendor/bundle/ruby/2.3.0/gems/redis-4.0.1/lib/redis/client.rb:98:in `connect'
remote:        /tmp/build_bb0aab9efc24beefd4555b836ba50433/vendor/bundle/ruby/2.3.0/gems/redis-4.0.1/lib/redis/client.rb:363:in `ensure_connected'
remote:        /tmp/build_bb0aab9efc24beefd4555b836ba50433/vendor/bundle/ruby/2.3.0/gems/redis-4.0.1/lib/redis/client.rb:219:in `block in process'
remote:        /tmp/build_bb0aab9efc24beefd4555b836ba50433/vendor/bundle/ruby/2.3.0/gems/redis-4.0.1/lib/redis/client.rb:304:in `logging'
remote:        /tmp/build_bb0aab9efc24beefd4555b836ba50433/vendor/bundle/ruby/2.3.0/gems/redis-4.0.1/lib/redis/client.rb:218:in `process'
remote:        /tmp/build_bb0aab9efc24beefd4555b836ba50433/vendor/bundle/ruby/2.3.0/gems/redis-4.0.1/lib/redis/client.rb:118:in `call'
remote:        /tmp/build_bb0aab9efc24beefd4555b836ba50433/vendor/bundle/ruby/2.3.0/gems/redis-4.0.1/lib/redis.rb:543:in `block in keys'
remote:        /tmp/build_bb0aab9efc24beefd4555b836ba50433/vendor/bundle/ruby/2.3.0/gems/redis-4.0.1/lib/redis.rb:45:in `block in synchronize'
remote:        /tmp/build_bb0aab9efc24beefd4555b836ba50433/vendor/bundle/ruby/2.3.0/gems/redis-4.0.1/lib/redis.rb:45:in `synchronize'
remote:        /tmp/build_bb0aab9efc24beefd4555b836ba50433/vendor/bundle/ruby/2.3.0/gems/redis-4.0.1/lib/redis.rb:542:in `keys'
remote:        /tmp/build_bb0aab9efc24beefd4555b836ba50433/config/application.rb:49:in `block in <class:Application>'
remote:        /tmp/build_bb0aab9efc24beefd4555b836ba50433/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.10/lib/active_support/lazy_load_hooks.rb:36:in `execute_hook'
remote:        /tmp/build_bb0aab9efc24beefd4555b836ba50433/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.10/lib/active_support/lazy_load_hooks.rb:45:in `block in run_load_hooks'
remote:        /tmp/build_bb0aab9efc24beefd4555b836ba50433/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.10/lib/active_support/lazy_load_hooks.rb:44:in `each'
remote:        /tmp/build_bb0aab9efc24beefd4555b836ba50433/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.10/lib/active_support/lazy_load_hooks.rb:44:in `run_load_hooks'
remote:        /tmp/build_bb0aab9efc24beefd4555b836ba50433/vendor/bundle/ruby/2.3.0/gems/railties-4.2.10/lib/rails/application/finisher.rb:62:in `block in <module:Finisher>'
remote:        /tmp/build_bb0aab9efc24beefd4555b836ba50433/vendor/bundle/ruby/2.3.0/gems/railties-4.2.10/lib/rails/initializable.rb:30:in `instance_exec'
remote:        /tmp/build_bb0aab9efc24beefd4555b836ba50433/vendor/bundle/ruby/2.3.0/gems/railties-4.2.10/lib/rails/initializable.rb:30:in `run'
remote:        /tmp/build_bb0aab9efc24beefd4555b836ba50433/vendor/bundle/ruby/2.3.0/gems/railties-4.2.10/lib/rails/initializable.rb:55:in `block in run_initializers'
remote:        /tmp/build_bb0aab9efc24beefd4555b836ba50433/vendor/bundle/ruby/2.3.0/gems/railties-4.2.10/lib/rails/initializable.rb:54:in `run_initializers'
remote:        /tmp/build_bb0aab9efc24beefd4555b836ba50433/vendor/bundle/ruby/2.3.0/gems/railties-4.2.10/lib/rails/application.rb:352:in `initialize!'
remote:        /tmp/build_bb0aab9efc24beefd4555b836ba50433/config/environment.rb:5:in `<top (required)>'
remote:        /tmp/build_bb0aab9efc24beefd4555b836ba50433/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:274:in `require'
remote:        /tmp/build_bb0aab9efc24beefd4555b836ba50433/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:274:in `block in require'
remote:        /tmp/build_bb0aab9efc24beefd4555b836ba50433/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:240:in `load_dependency'
remote:        /tmp/build_bb0aab9efc24beefd4555b836ba50433/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:274:in `require'
remote:        /tmp/build_bb0aab9efc24beefd4555b836ba50433/vendor/bundle/ruby/2.3.0/gems/railties-4.2.10/lib/rails/application.rb:328:in `require_environment!'
remote:        /tmp/build_bb0aab9efc24beefd4555b836ba50433/vendor/bundle/ruby/2.3.0/gems/railties-4.2.10/lib/rails/application.rb:457:in `block in run_tasks_blocks'
remote:        /tmp/build_bb0aab9efc24beefd4555b836ba50433/vendor/bundle/ruby/2.3.0/gems/sprockets-rails-3.2.1/lib/sprockets/rails/task.rb:62:in `block (2 levels) in define'
remote:        /tmp/build_bb0aab9efc24beefd4555b836ba50433/vendor/bundle/ruby/2.3.0/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
remote:        Tasks: TOP => environment

```

My initializers/redis.rb
```
require 'redis'

if Rails.env.development?
  $redis = Redis.new
else
  $redis = Redis.new(:url => ENV['REDISTOGO_URL'])
end
```

My application.rb
```
    config.after_initialize do
      # Clean redis data 
      redis_keys = $redis.keys("some_keys")
      redis_keys.each do |key|
        if !key.include? "buffer"
          $redis.del(key)
        end
      end
    end
```

Did you guys figure out how to fix it? 
Thank you in advanced for your help.

Cheers,
Tina.

**Comment by byroot** [comment]
`Error connecting to Redis on 127.0.0.1:6379` so clearly `$REDISTOGO_URL` is `nil`.

This has nothing to do with your update, it's just that your env var was cleared before, and deploying restarted the processes causing them to reboot without the needed environment.

This is a heroku hosting issue, not a Redis one.
